recipes/urls.py
from django.urls import path
from recipes.views import recipe_list, show_recipe, add_recipe, edit_recipe, share_recipe, rate_recipe, add_recipe_ingredient, add_recipe_step
from django.shortcuts import redirect
from . import views

def redirect_to_recipes(request):
    return redirect('recipe_list')

urlpatterns = [
    path('', views.recipe_list, name='recipe_list'),
    path('recipes/add/', add_recipe, name='add_recipe'),
    path('recipes/<int:id>/', show_recipe, name='recipe_detail'),
    path('recipes/edit/<int:id>/', edit_recipe, name='edit_recipe'),
    path('', redirect_to_recipes, name="home"),
    path('recipe/<int:recipe_id>/add_step/', views.add_recipe_step, name='add_recipe_step'),
    path('recipe/<int:recipe_id>/add_ingredient/', views.add_recipe_ingredient, name='add_recipe_ingredient'),
    path('recipes/<int:id>/share/', share_recipe, name='share_recipe'),
    path('recipes/<int:recipe_id>/rate/', views.rate_recipe, name='rate_recipe'),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
]

recipes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    picture = models.URLField()
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=False, default=0.00)
    prep_time = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    cook_time = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    serves = models.IntegerField(null=False, default=1)

    def __str__(self):
        return self.title

    def update_rating(self):
        total_ratings = self.ratings.count()
        if total_ratings > 0:
            self.rating = sum(rating.value for rating in self.ratings.all()) / total_ratings
            self.save()

class Rating(models.Model):
    recipe = models.ForeignKey(Recipe, related_name='ratings', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.PositiveSmallIntegerField()

    class Meta:
        unique_together = ('recipe', 'user')
    def get_absolute_url(self):
        return reverse('recipe_detail', args=[self.id])

class RecipeStep(models.Model):
    step_number = models.PositiveSmallIntegerField()
    instruction = models.TextField()
    recipe = models.ForeignKey(Recipe, related_name='steps', on_delete=models.CASCADE)

    class Meta:
        ordering = ['step_number']

class RecipeIngredient(models.Model):
    MEASURE_CHOICES = [
        ('oz', 'Ounces'),
        ('qt', 'Quart'),
        ('pt', 'Pint'),
        ('gal', 'Gallon'),
        ('tsp', 'Teaspoon'),
        ('tbsp', 'Tablespoon'),
        ('cup', 'Cup'),
        ('sprinkle', 'Sprinkle'),
        ('smidge', 'Smidge'),
        ('cloves', 'Cloves'),
        ('bushel', 'Bushel'),
        ('bunch', 'Bunch'),
        ('whole', 'Whole'),
        ('pound', 'Pound')
    ]
    name = models.CharField(max_length=200)
    quantity = models.CharField(max_length=50)
    measure = models.CharField(max_length=20, choices=MEASURE_CHOICES, default='oz')
    instruction = models.TextField(null=True, blank=True)
    recipe = models.ForeignKey(Recipe, related_name='ingredients', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

recipes/forms.py
from django.forms import ModelForm
from .models import Recipe, RecipeStep, RecipeIngredient, Rating
from django import forms

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        exclude = ['created_on']
        widgets = {
            'description': forms.Textarea(attrs={'rows':3, 'cols':40})
        }

class RecipeStepForm(ModelForm):
    class Meta:
        model = RecipeStep
        fields = ['step_number', 'instruction']
        widgets = {
            'instruction': forms.Textarea(attrs={'rows':3, 'cols':40})
        }

class RecipeIngredientForm(ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['name', 'quantity', 'measure','instruction']
        widgets = {
            'instruction': forms.Textarea(attrs={'rows':3, 'cols':40})
        }
class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['value']
        widgets = {
            'value': forms.RadioSelect(choices=[(i, str(i)) for i in range(1, 6)]),
        }

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Recipe, RecipeStep, RecipeIngredient, Rating
from .forms import RecipeForm, RecipeStepForm, RecipeIngredientForm, RatingForm
from django.db.models import Q
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

@login_required
def show_recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    rating_form = RatingForm()
    ingredients = recipe.ingredients.all()
    steps = recipe.steps.all()
    context = {
        'recipe_object': recipe,
        'rating_form': rating_form,
        'ingredients': ingredients,
        'steps': steps,
    }
    return render(request, 'recipes/detail.html', context)

def recipe_list(request):
    query = request.GET.get('q')
    if query:
        recipes = Recipe.objects.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(ingredients__name__icontains=query) |
            Q(ingredients__quantity__icontains=query) |
            Q(steps__instruction__icontains=query)
        ).distinct()
    else:
        recipes = Recipe.objects.all()

    context = {
        "recipe_list": recipes,
        "query": query,
    }
    return render(request, "recipes/list.html", context)

@login_required
def add_recipe(request):
    RecipeStepFormSet = modelformset_factory(RecipeStep, form=RecipeStepForm, extra=1,can_delete=True)
    RecipeIngredientFormSet = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=1,can_delete=True)

    if request.method == 'POST':
        form = RecipeForm(request.POST)
        steps_formset = RecipeStepFormSet(request.POST, queryset=RecipeStep.objects.none(), prefix='steps')
        ingredients_formset = RecipeIngredientFormSet(request.POST, queryset=RecipeIngredient.objects.none(), prefix='ingredients')

        if form.is_valid() and steps_formset.is_valid() and ingredients_formset.is_valid():
            recipe = form.save()
            for step_form in steps_formset:
                step = step_form.save(commit=False)
                step.recipe = recipe
                step.save()
            for ingredient_form in ingredients_formset:
                ingredient = ingredient_form.save(commit=False)
                ingredient.recipe = recipe
                ingredient.save()
            return redirect('recipe_list')
    else:
        form = RecipeForm()
        steps_formset = RecipeStepFormSet(queryset=RecipeStep.objects.none(), prefix='steps')
        ingredients_formset = RecipeIngredientFormSet(queryset=RecipeIngredient.objects.none(), prefix='ingredients')

    return render(request, 'recipes/add_recipe.html', {
        'form': form,
        'steps_formset': steps_formset,
        'ingredients_formset': ingredients_formset,
    })

@login_required
def edit_recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    RecipeStepFormSet = modelformset_factory(RecipeStep, form=RecipeStepForm, extra=1, can_delete=True)
    RecipeIngredientFormSet = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=1, can_delete=True)

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        steps_formset = RecipeStepFormSet(request.POST, queryset=RecipeStep.objects.filter(recipe=recipe), prefix='steps')
        ingredients_formset = RecipeIngredientFormSet(request.POST, queryset=RecipeIngredient.objects.filter(recipe=recipe), prefix='ingredients')

        if form.is_valid() and steps_formset.is_valid() and ingredients_formset.is_valid():
            form.save()
            for step_form in steps_formset:
                if step_form.cleaned_data:
                    if step_form.cleaned_data.get('DELETE'):
                        step_form.instance.delete()
                    else:
                        step = step_form.save(commit=False)
                        step.recipe = recipe
                        step.save()
            for ingredient_form in ingredients_formset:
                if ingredient_form.cleaned_data:
                    if ingredient_form.cleaned_data.get('DELETE'):
                        ingredient_form.instance.delete()
                    else:
                        ingredient = ingredient_form.save(commit=False)
                        ingredient.recipe = recipe
                        ingredient.save()
            return redirect('recipe_detail', id=recipe.id)
    else:
        form = RecipeForm(instance=recipe)
        steps_formset = RecipeStepFormSet(queryset=RecipeStep.objects.filter(recipe=recipe), prefix='steps')
        ingredients_formset = RecipeIngredientFormSet(queryset=RecipeIngredient.objects.filter(recipe=recipe), prefix='ingredients')

    return render(request, 'recipes/edit_recipe.html', {
        'form': form,
        'recipe': recipe,
        'steps_formset': steps_formset,
        'ingredients_formset': ingredients_formset,
    })

@login_required
def add_recipe_step(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == "POST":
        step_number = request.POST.get('step_number')
        instruction = request.POST.get('instruction')
        if step_number and instruction:
            RecipeStep.objects.create(recipe=recipe, step_number=step_number, instruction=instruction)
        return redirect('recipe_detail', id=recipe.id)  # Ensure this redirects to 'recipe_detail'
    return render(request, 'recipes/detail.html', {'recipe': recipe})

@login_required
def add_recipe_ingredient(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == "POST":
        name = request.POST.get('name')
        quantity = request.POST.get('quantity')
        if name and quantity:
            RecipeIngredient.objects.create(recipe=recipe, name=name, quantity=quantity)
        return redirect('recipe_detail', id=recipe.id)  # Ensure this redirects to 'recipe_detail'
    return render(request, 'recipes/detail.html', {'recipe': recipe})

@login_required
def share_recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    if request.method == "POST":
        email = request.POST.get('email')
        message = request.POST.get('message', '')
        subject = f"Check out this recipe: {recipe.title}"
        recipe_url = request.build_absolute_uri(recipe.get_absolute_url())
        email_body = f"{message}\n\nYou can view the recipe at: {recipe_url}"

        send_mail(
            subject,
            email_body,
            settings.DEFAULT_FROM_EMAIL,
            [email],
        )
        return redirect('recipe_detail', id=recipe.id)
    return render(request, 'recipes/share_recipe.html', {'recipe': recipe})

@login_required
def rate_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating, content = Rating.objects.update_or_create(
                recipe=recipe,
                user=request.user,
                defaults={'value': form.cleaned_data['value']}
            )
            recipe.update_rating()
            return redirect('recipe_detail', id=recipe.id)
    else:
        form = RatingForm()

    context = {
        'form': form,
        'recipe': recipe
    }
    return render(request, 'recipes/rate_recipe.html', context)

recipes/templates/recipes/add_recipe.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block title %}Add Recipe{% endblock %}

{% block content %}
    <h1>Add Recipe</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <h2>Ingredients</h2>
        {{ ingredients_formset.management_form }}
        <div id="ingredients-formset">
            {% for form in ingredients_formset %}
                <div class="ingredients-formset-item">
                    {{ form.as_p }}
                    <button type="button" class="remove-ingredient">Remove</button>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-ingredient">Add Ingredient</button>

        <h2 class="form-section-title">Steps</h2>
        {{ steps_formset.management_form }}
        <div id="steps-formset">
            {% for form in steps_formset %}
                <div class="steps-formset-item">
                    {{ form.as_p }}
                    <button type="button" class="remove-step">Remove</button>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-step">Add Step</button>

        <div class="save-button-wrapper">
            <button type="submit" class="save-changes-button">Save Changes</button>
        </div>
    </form>
{% endblock %}

recipes/templates/recipes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Scrumptious Recipes{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/recipes.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'recipe_list' %}">Main page</a>
            {% if user.is_authenticated %}
                <a href="{% url 'add_recipe' %}" class="add-recipe-button">Add a new recipe</a>
                <span>Hello, {{ user.username }}!</span>
                <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" style="background: none; border: none; color: #0000EE; text-decoration: underline; cursor: pointer;">Log out</button>
                </form>
            {% else %}
                <a href="{% url 'signup' %}">Sign up</a>
                <a href="{% url 'login' %}">Log in</a>
            {% endif %}
        </nav>
        {% if user.is_authenticated %}
        <form method="get" action="{% url 'recipe_list' %}" class="search-form">
            <input type="text" name="q" placeholder="Search recipes..." value="{{ query|default_if_none:'' }}">
            <button type="submit">Search</button>
        </form>
        {% endif %}
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>Made with <span class="heart-word">love<span class="heart-explosion">❤️</span></span> by Scrumptious Recipes</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.recipes-carousel').slick({
                slidesToShow: 3,
                slidesToScroll: 3,
                arrows: true,
                dots: true,
                autoplay: false,
                autoplaySpeed: 2000,
                prevArrow: '<button class="slick-prev">&lt;</button>',
                nextArrow: '<button class="slick-next">&gt;</button>'
            });
        });
    </script>
    <script src="{% static 'js/formset.js' %}"></script>
</body>
</html>

recipes/templates/recipes/detail.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block title %}{{ recipe_object.title }}{% endblock %}

{% block content %}
<div class="detail-page">
    <h1>{{ recipe_object.title }}</h1>
    <img src="{{ recipe_object.picture }}" alt="{{ recipe_object.title }}">

    <p>{{ recipe_object.description }}</p>

    <div class="recipe-grid">
        <div class="ingredients-section">
            <h3>Ingredients</h3>
            <ul class="ingredients-list">
                {% for ingredient in ingredients %}
                    <li>
                        <span class="ingredient-name">{{ ingredient.name }}</span>:
                        <span class="ingredient-quantity">{{ ingredient.quantity }} {{ ingredient.get_measure_display }}</span>
                        {% if ingredient.instruction %}
                            <span class="ingredient-instruction"> - {{ ingredient.instruction }}</span>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="steps-section">
            <h3>Steps</h3>
            <ol class="steps-list">
                {% for step in recipe_object.steps.all %}
                <li>{{ step.instruction }}</li>
                {% endfor %}
            </ol>
        </div>
    </div>
    <h2>Rating</h2>
    <p>Current Rating: {{ recipe_object.rating }}</p>
    <form method="post" action="{% url 'rate_recipe' recipe_object.id %}">
        {% csrf_token %}
        {{ rating_form.as_p }}
        <button type="submit">Submit Rating</button>
    </form>
    <a href="{% url 'share_recipe' recipe_object.id %}" class="share-recipe-button">Share</a>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/edit_recipe.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block title %}Edit Recipe{% endblock %}

{% block content %}
    <h1>Edit Recipe</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <h2>Ingredients</h2>
        {{ ingredients_formset.management_form }}
        <div id="ingredients-formset">
            {% for form in ingredients_formset %}
                <div class="ingredients-formset-item">
                    {{ form.as_p }}
                    <button type="button" class="remove-ingredient">Remove</button>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-ingredient">Add Ingredient</button>

        <h2 class="form-section-title">Steps</h2>
        {{ steps_formset.management_form }}
        <div id="steps-formset">
            {% for form in steps_formset %}
                <div class="steps-formset-item">
                    {{ form.as_p }}
                    <button type="button" class="remove-step">Remove</button>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-step">Add Step</button>

        <div class="save-button-wrapper">
            <button type="submit" class="save-changes-button">Save Changes</button>
        </div>
    </form>
{% endblock %}

recipes/templates/recipes/list.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block title %}Scrumptious Recipes{% endblock %}

{% block content %}
    <h1>Scrumptious Recipes</h1>
    <h2 class="animate-eating">
        <span>All</span> <span>the</span> <span>food</span> <span>that's</span> <span>fit</span> <span>to</span> <span>eat</span>
        <div class="pacman">
            <div class="pacman__eye"></div>
            <div class="pacman__mouth"></div>
        </div>
    </h2>
    <div class="recipes-carousel">
        {% for recipe in recipe_list %}
        <div class="recipe">
            <div class="recipe-card">
                <h3><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.title }}</a></h3>
                <a href="{% url 'recipe_detail' recipe.id %}"><img src="{{ recipe.picture }}" alt="{{ recipe.title }}"></a>
                <div>{{ recipe.rating }} stars</div>
                {% if user.is_authenticated %}
                    <a href="{% url 'edit_recipe' recipe.id %}" class="edit-recipe-button">Edit</a>
                {% endif %}
            </div>
        </div>
        {% empty %}
        <p>No recipes found matching your query.</p>
        {% endfor %}
    </div>
{% endblock %}

recipes/templates/recipes/share_recipe.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block title %}Share Recipe{% endblock %}

{% block content %}
    <h1>Share Recipe: {{ recipe.title }}</h1>
    <form method="post">
        {% csrf_token %}
        <label for="email">Recipient's Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="message">Message:</label>
        <textarea id="message" name="message" rows="4" cols="50"></textarea>
        <br>
        <button type="submit">Send</button>
    </form>
{% endblock %}